---
- name: My Loops Playbook
  hosts: demo
  remote_user: ansible
  become: yes
  connection: ssh

  tasks:
    - name: Add list of users in my nodes
      user:
        name: "{{ item }}"
        state: present
      loop:
        - Bhupinder
        - Sachin
        - einstein
        - vascodgama
